### PR TITLE
Fixes for #1209

### LINKED ISSUE #1209: Code smell: String literal "/paths" is being duplicated
I am running a fork of Zally attached to Sonarqube and there is a code smell because the string literal "/paths" is being duplicated in multiple places.

### PR DESCRIPTION
**Pull request by tharakadesilva**
Fixes #1209

### CODE REVIEW

**Comment by tkrop** [comment]
:+1:

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt [hunk 1]
```diff
@@ -48,6 +49,9 @@ class ReverseAst internal constructor(
     }
 
     companion object {
+        const val pathsJsonPointerString = "/paths"
```
Comment (vadeg) [inline server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt:52]: Please follow [kotlin guidelines](https://kotlinlang.org/docs/coding-conventions.html#property-names) for naming.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt [hunk 2]
```diff
@@ -48,6 +49,9 @@ class ReverseAst internal constructor(
...
+        val pathsJsonPointer = pathsJsonPointerString.toJsonPointer()
```
Comment (vadeg) [inline server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt:53]: Same here about Kotlin guidelines.

**Review by vadeg — CHANGES_REQUESTED** [review]
Hi @tharakadesilva !

Thank you for your contribution, but I don't think that `ReverseAst` is the right place to define `paths` property. This is a part of OpenAPI / Swagger spec. I think it should be somewhere in the `Context` or as an extension for `OpenAPI` or `Swagger` classes.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt (hunk 1 above)
Comment (tharakadesilva) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt]: Fixed.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt (hunk 2 above)
Comment (tharakadesilva) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt]: Fixed.

**Comment by tharakadesilva** [comment]
> Hi @tharakadesilva !
> 
> Thank you for your contribution, but I don't think that `ReverseAst` is the right place to define `paths` property. This is a part of OpenAPI / Swagger spec. I think it should be somewhere in the `Context` or as an extension for `OpenAPI` or `Swagger` classes.

Hi @vadeg, thank you for the feedback. I am a little torn on where to move these. I feel that the recommendation to move it as an extension to `OpenAPI` is the best approach. `OpenAPI` already has some extensions in the `OpenApiUtil.kt` file. Do you think that this might be a good place to place these values as well?

**Comment by vadeg** [comment]
@tharakadesilva I would suggest something like this
```
class OpenApiPaths {
    companion object {
        const val PATHS = "/paths"
    }
}
```
Unfortunately, Kotlin [doesn't support](https://youtrack.jetbrains.com/issue/KT-11968) static extensions for Java classes and the original idea to make someting like 
```
io.swagger.v3.oas.models.Paths
val Paths.paths: String 
    get() = "sdafa"
```
and use like `Paths.paths` will not work.

**Comment by tharakadesilva** [comment]
@vadeg I have fixed the code as you suggested. Would appreciate it if you could review it again now.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package org.zalando.zally.core.util
+
+import org.zalando.zally.core.toJsonPointer
+
+class OpenApiPaths {
+    companion object {
+        const val PATHS_JSON_POINTER_STRING = "/paths"
+        val PATHS_JSON_POINTER = PATHS_JSON_POINTER_STRING.toJsonPointer()
```
Comment (vadeg) [inline server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt:8]: I thinks this is not needed here, because it is up to the client how to interpret the string.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt [hunk 4]
```diff
@@ -0,0 +1,10 @@
+package org.zalando.zally.core.util
+
+import org.zalando.zally.core.toJsonPointer
+
+class OpenApiPaths {
+    companion object {
+        const val PATHS_JSON_POINTER_STRING = "/paths"
```
Comment (vadeg) [inline server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt:7]: This is not a JSON pointer but a json path. Could you rename it to `PATHS`?

**Review by vadeg — COMMENTED** [review]
Hi @tharakadesilva 

Sorry for the delay. I have left a couple of comments.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt (hunk 3 above)
Comment (tharakadesilva) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt]: I have removed this.

File: server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt (hunk 4 above)
Comment (tharakadesilva) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt]: @vadeg I renamed this to `PATHS`. However, now I feel that the class name `OpenApiPaths` might not appropriate anymore. I was thinking about renaming `OpenApiSections`, what do you think?

Comment (vadeg) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt]: Good idea.

Comment (tharakadesilva) [reply server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt]: Fixed.

**Comment by tharakadesilva** [comment]
> Hi @tharakadesilva
> 
> Sorry for the delay. I have left a couple of comments.

Hi @vadeg, thank you for the feedback. I have addressed the comments and I think it is ready for a review again. Thank you for the continuous feedback :)

**Review by vadeg — APPROVED** [review]
@tharakadesilva thank you very much for your contribution!

**Comment by vadeg** [comment]
👍

**Comment by tkrop** [comment]
:+1:
