### PR TITLE
Fix Use429HeaderForRateLimitRule NullPointerException on paths that have no response

### LINKED ISSUE #787: TargetInvocationException: null
# How to reproduce

Lint this API in Zally.

```yaml
swagger: "2.0"
info:
  x-audience: business-unit-internal
  x-api-id: d0184f38-b98d-11e7-9c56-68f728c1ba70
  title: foo
  description: bar
  version: 1.0.0
  contact:
    email: a@b.c
    name: James Bond
    url: https://www.mi6.co.gov
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: https://identity.example.com/oauth2/token
    scopes:
      lalala.read: Access right needed to read
      lalala.write: Access right needed to write
paths: 
  /foos/bars:
    get:
      description: asd
```

The front end will answer:

> ERROR
> Ooops something went wrong!

The server will log:
```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at de.zalando.zally.rule.RulesValidator.invoke(RulesValidator.kt:60) ~[main/:na]
...
Caused by: java.lang.NullPointerException: null
	at de.zalando.zally.rule.zalando.Use429HeaderForRateLimitRule.checkHeadersForRateLimiting(Use429HeaderForRateLimitRule.kt:22) ~[classes!/:na]

```

### PR DESCRIPTION
**Pull request by roxspring**
- Added test demonstrating problem to prevent recurrence.
- Simple fix with `.orEmpty()` calls.
- Refactored to use a new `Context.validateResponses()` for future shared safety.

Closes #787

### CODE REVIEW

File: server/src/test/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRuleTest.kt [hunk 1]
```diff
@@ -45,4 +49,21 @@ class Use429HeaderForRateLimitRuleTest {
 
         assertThat(violations).isEmpty()
     }
+
+    @Test
+    fun `checkHeadersForRateLimiting avoid bug 787 NPE on missing response`() {
```
Comment (tkrop) [inline server/src/test/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRuleTest.kt]: It looks strange to have this check here, but not in other rules that may/will fail too. We should have general test patterns for NPEs in OpenAPI schemas which should be checked on every rule. @roxspring are you interested in providing a solution?

File: server/src/main/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRule.kt [hunk 2]
```diff
@@ -19,11 +20,14 @@ class Use429HeaderForRateLimitRule {
 
     @Check(severity = Severity.MUST)
     fun checkHeadersForRateLimiting(context: Context): List<Violation> =
-        context.api.paths.values.flatMap { it.readOperations().flatMap { it.responses.entries } }
-            .filter { (code, _) -> "429" == code }.map { it.value }
-            .filterNot { containsRateLimitHeader(it.headers.orEmpty().keys) }
-            .map { context.violation(description, it) }
+        context.validateResponses(responseFilter = this::violatingResponse) { (_, response) ->
```
Comment (ddufourboivin-zalando) [inline server/src/main/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRule.kt]: I do not think the ``this::`` is required here.

**Comment by ddufourboivin-zalando** [comment]
👍

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

File: server/src/test/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRuleTest.kt (hunk 1 above)
Comment (roxspring) [reply server/src/test/java/de/zalando/zally/rule/zalando/Use429HeaderForRateLimitRuleTest.kt]: Test added here purely because I was working TDD style. Happy to move it somewhere more specific - presumably a test for DefaultContext.

Do you have a more specific suggestion? A niaive approach to generally testing the NPEs would be to just manually add a whole bunch of NPE focused unit tests - which doesn't sound much fun and is likely to still have gaps unless we hit 100% path coverage.

Kotlin generally does a nice job of avoiding NPEs at compile time, but this is undermined here by using Java object models (Swagger, OpenAPI) that are assumed to be non-null responses. Is there any mechanism to tell Kotlin / Idea to assume these are nullable responses instead? (suspect @ddufourboivin-zalando might know).
