### PR TITLE
Fixing StackoverFlow, Adding tests for NPE and support for recursive specifications

### LINKED ISSUE #826: Checking recursive APIs schemas result in StackOverflowException
Example: https://github.bus.zalan.do/setanta/api-reviews/pull/1/files

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Closes #826

This PR includes:
- Fix for the `StackOverflowError` in one of the rule checks
- A general test for all checks to prevent further `StackOverflowError`s
- A general test for all checks to check whether they can cope with empty specifications

### CODE REVIEW

File: server/src/main/java/de/zalando/zally/rule/zalando/MediaTypesRule.kt [hunk 1]
```diff
@@ -24,8 +24,8 @@ class MediaTypesRule {
     @Check(severity = Severity.SHOULD)
     fun validate(context: Context): List<Violation> =
         context.validateOperations { (_, operation) ->
-            val consumedMediaTypes = operation.requestBody?.content?.entries.orEmpty()
-            val producedMediaTypes = operation.responses?.values.orEmpty()
+            val consumedMediaTypes = operation.requestBody?.content?.entries.orEmpty().toList()
+            val producedMediaTypes = operation.responses?.values.orEmpty().toList()
```
Comment (ddufourboivin-zalando) [inline server/src/main/java/de/zalando/zally/rule/zalando/MediaTypesRule.kt]: Just curious about why you need to transform them to `List`?

Comment (maxim-tschumak) [reply server/src/main/java/de/zalando/zally/rule/zalando/MediaTypesRule.kt]: > Oh ... actually ... is THAT the fix? By using an explicit list, elements do not end up in a Set or anything Hash-based et voilà! Problem gelöst! ...?

Yes, this was the problem! We should always avoid using `.toString` and `.hashCode` on the elements of the `OpenAPI` object - it will fail for recursive specifications.

**Comment by maxim-tschumak** [comment]
:+1:

File: server/src/test/java/de/zalando/zally/apireview/ApiViolationsControllerTest.kt [hunk 2]
```diff
@@ -26,10 +29,71 @@ class ApiViolationsControllerTest {
...
+            .andExpect(status().isOk)
+    }
+
+    /**
+     * This test runs all rules against an empty OpenAPI object. It checks for possible NPE in the check implementation
+     * when traversing the OpenAPI object tree. By having this test in place we don't have to write such a test for each
+     * rule.
+     */
+    @Test
+    fun `all rules must be able to cope with empty (minimal) api specifications`() {
```
Comment (tkrop) [inline server/src/test/java/de/zalando/zally/apireview/ApiViolationsControllerTest.kt]: Here is the place where we should be more generic and generate all kinds of incomplete specifications with implicit and explicit `null` values. The problem is how this generator should look like ... the minimal approach I would choose is providing a basic template and successively replacing values against `null` and removing leaves. until the template is empty.

Comment (tkrop) [reply server/src/test/java/de/zalando/zally/apireview/ApiViolationsControllerTest.kt]: Should be fixed by #832.
