### PR TITLE
fix: scope validation (#1251)

### LINKED ISSUE #1251: "MUST Secure Endpoints" violation using Bearer Auth
Even with the implementation of #1247, our builds still fails due to violating `MUST Secure Endpoints` endpoints saying e.g. `The scope 'BearerAuth/wrapping-eligibility.read' is not specified in the clientCredentials flow of the OAuth2 security definition` (see https://sunrise.zalando.net/cdp/ghe/broadway/wrapping-eligibility/l-2fdr94fskn5ymahu4h82yvirbc/steps/0/logs for details).

As the RESTful API guidelines do not mention anything about specifying scope information, either the check needs to be adjusted or something is missing in the guidelines.

### PR DESCRIPTION
**Pull request by tkrop**
fixes #1251.

We need to filter scope validation for other authentication schemes different from `OAuth2` so far.

### CODE REVIEW

File: server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt [hunk 1]
```diff
@@ -42,30 +42,31 @@ class SecureAllEndpointsRule {
...
+        val specifiedSchemes = context.api.components?.securitySchemes?.entries.orEmpty()
+            .map { (group, scheme) -> group to scheme }.toMap()
+
+        val specifiedScopes = context.api.components?.securitySchemes?.entries.orEmpty()
+            .filter { (_, scheme) -> scheme.type == SecurityScheme.Type.OAUTH2 }
             .flatMap { (group, scheme) ->
-                scheme.flows?.clientCredentials?.scopes.orEmpty().keys.map { scope -> group to scope }
-            }
-            .toSet()
+                scheme.flows?.clientCredentials?.scopes
```
Comment (tkrop) [inline server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt:51]: I think we should iterate over all OAuth2 flows here, but I'm not sure how this would look like.

File: server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt [hunk 2]
```diff
@@ -42,30 +42,31 @@ class SecureAllEndpointsRule {
...
         if (!context.isOpenAPI3()) return emptyList()
 
-        val specifiedScopes = context.api.components?.securitySchemes?.entries
-            .orEmpty()
-            .filter { (_, scheme) -> SecurityScheme.Type.OAUTH2 == scheme.type }
+        val specifiedSchemes = context.api.components?.securitySchemes?.entries.orEmpty()
+            .map { (group, scheme) -> group to scheme }.toMap()
+
+        val specifiedScopes = context.api.components?.securitySchemes?.entries.orEmpty()
+            .filter { (_, scheme) -> scheme.type == SecurityScheme.Type.OAUTH2 }
```
Comment (vadeg) [inline server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt:49]:
```suggestion
            .filter { (_, scheme) -> scheme.isOAuth2()}
```

File: server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt (hunk 1 above)
Comment (vadeg) [reply server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt:51]: There is a function `SecurityScheme.allScopes()` which returns all scopes.

File: server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt (hunk 2 above)
Comment (tkrop) [reply server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt]: Changed.

File: server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt (hunk 1 above)
Comment (tkrop) [reply server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/SecureAllEndpointsRule.kt]: Good hint. Found a solution using `allFlows()`.

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by vadeg** [comment]
👍
