### PR TITLE
Bugfix: Do not check format of null schemas

### LINKED ISSUE #803: FormatForNumbersRule explodes on missing schemas
The following definition results in a `NullPointerException` because the examples have a `null` schema which we then fail to check for number format:

```yaml
swagger: '2.0'
info:
  title: Minimal API
  version: 1.0.0
paths:
  /handlers:
    get:
      responses:
        200:
          description: OK
          examples:
            application/json:
              - name: Named thing
```

### PR DESCRIPTION
**Pull request by roxspring**
Closes #803

### CODE REVIEW

File: server/src/main/java/de/zalando/zally/util/OpenAPIObjectUtils.kt [hunk 1]
```diff
@@ -8,17 +8,18 @@ import io.swagger.v3.oas.models.media.Schema
  * @param api OpenAPI 3 specification object
  * @return a collection of schemas
  */
-fun allSchemas(api: OpenAPI): Collection<Schema<Any>> = api.components.schemas.orEmpty().values +
-    api.components.responses.values.flatMap { it.content.values.map { it.schema } } +
-    api.components.requestBodies.values.flatMap { it.content.values.map { it.schema } } +
+fun allSchemas(api: OpenAPI): Collection<Schema<Any>> =
+    api.components.schemas.orEmpty().values +
+    api.components.responses.values.flatMap { it.content.values.mapNotNull { it.schema } } +
+    api.components.requestBodies.values.flatMap { it.content.values.mapNotNull { it.schema } } +
```
Comment (ddufourboivin-zalando) [inline server/src/main/java/de/zalando/zally/util/OpenAPIObjectUtils.kt]: Which editor and settings are you using to have the multiline operations aligned like this?

**Comment by ddufourboivin-zalando** [comment]
👍

File: server/src/main/java/de/zalando/zally/util/OpenAPIObjectUtils.kt (hunk 1 above)
Comment (roxspring) [reply server/src/main/java/de/zalando/zally/util/OpenAPIObjectUtils.kt]: IntelliJ defaults, but with some hand editing since you guys keep correcting the 8 character "Continuation indent". The linebreak after `=` was by hand primarily because lining it up made it easier to keep my head around what was going on as I hunted down the `NullPointerException`.

**Comment by maxim-tschumak** [comment]
:+1:
