### PR TITLE
fix: common fields rule (#747)

### LINKED ISSUE #747: Check for Zalando rule #174 false-positive
Zalando rule 174 checks for proper usage of common fields. The Guideline states the field `type` must have the type `string`.

The rule check doesn't check the type of referenced definition and generates a violation if the type is not set explicitly.

**Example / How to reproduce** The Zally Server API specification:
The `Rule` definition contains a `type` field which references to the definition of the `RuleType`. The type of the `RuleType` is `x-extensible-enum`, which is also a string.
So technically, the type of the `type` field of the `Rule` definition is `string` and the check should not produce any violations

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Related to #714 
Fixes #747

### CODE REVIEW

File: server/src/test/java/de/zalando/zally/rule/zalando/CommonFieldTypesRuleTest.kt [hunk 1]
```diff
@@ -1,93 +1,206 @@
...
-        assertThat(rule.checkField("id", StringProperty())).isNull()
-        assertThat(rule.checkField("id", StringProperty("UUID"))).isNull()
-        assertThat(rule.checkField("created", StringProperty("date-time"))).isNull()
-        assertThat(rule.checkField("modified", StringProperty("date-time"))).isNull()
-        assertThat(rule.checkField("type", StringProperty())).isNull()
+    fun `checkField matching should be case insensitive`() {
+        assertThat(rule.checkField("iD", createSchema(INTEGER_TYPE, null))).isNotNull()
+        assertThat(rule.checkField("CREATED", createSchema(INTEGER_TYPE, null))).isNotNull()
+        assertThat(rule.checkField("tYpE", createSchema(null, null))).isNotNull()
+        assertThat(rule.checkField("CREated", createSchema(STRING_TYPE, "time"))).isNotNull()
```
Comment (tkrop) [inline server/src/test/java/de/zalando/zally/rule/zalando/CommonFieldTypesRuleTest.kt]: By the way, we should introduce some synonyms rule: `created` -> `created_at`, `modified` -> `modified_at`.

File: server/src/test/java/de/zalando/zally/rule/zalando/CommonFieldTypesRuleTest.kt [hunk 2]
```diff
@@ -1,93 +1,206 @@
...
+              /pets:
+                get:
+                  responses:
+                    200:
+                      content:
+                        application/json:
+                          schema:
+                            properties:
+                              id:
+                                "${'$'}ref": "#/components/schemas/CustomId"
```
Comment (tkrop) [inline server/src/test/java/de/zalando/zally/rule/zalando/CommonFieldTypesRuleTest.kt]: Unfortunately, this is not the only allowed place for a reference.

Comment (maxim-tschumak) [reply server/src/test/java/de/zalando/zally/rule/zalando/CommonFieldTypesRuleTest.kt]: It's a representative test - we don't want to test the resolve feature of the `swagger-parser`.

**Comment by maxim-tschumak** [comment]
Now, the rule also checks all the nested properties recursively. @tkrop please have another look

**Comment by maxim-tschumak** [comment]
:+1:
