### PR TITLE
fix(server): StringPropertyLengthBoundsRule ignores enum strings #1137

### LINKED ISSUE #1137: Don't report StringPropertyLengthBoundsRule if property has enum
When a property of type string has an enum setting it does not make sense to specify minimum and maximum length. 

Reproduce with an object in a body or response like this:
```yaml
type: object
properties:
  fooBar:
    type: string
    enum: [foo, bar]
```

Gets complaint from rule S007 SHOULD Define bounds for lengths of string properties 

Expected: 
- Don’t insist on adding `minLength` and `maxLength`
- In fact it might make sense to complain if they are present

### PR DESCRIPTION
**Pull request by roxspring**
- No violations created when string property is an enum

Closes #1137

### CODE REVIEW

**Comment by vadeg** [comment]
Thank @roxspring!

**Comment by vadeg** [comment]
👍

File: server/zally-ruleset-zally/src/test/kotlin/de/zalando/zally/ruleset/zally/StringPropertyLengthBoundsRuleTest.kt [hunk 1]
```diff
@@ -280,4 +280,31 @@ class StringPropertyLengthBoundsRuleTest {
             .assertThat(violations)
             .isEmpty()
     }
+
+    @Test
+    fun `checkStringLengthBounds with enum returns no violations`() {
+        @Language("YAML")
+        val context = DefaultContextFactory().getOpenApiContext(
+            """
```
Comment (zeitlinger) [inline server/zally-ruleset-zally/src/test/kotlin/de/zalando/zally/ruleset/zally/StringPropertyLengthBoundsRuleTest.kt:288]: there is no min/max length in the test

Comment (roxspring) [reply server/zally-ruleset-zally/src/test/kotlin/de/zalando/zally/ruleset/zally/StringPropertyLengthBoundsRuleTest.kt:288]: That’s the intention - In the case of enums the min/max are implicitly defined by the shortest/longest accepted enum so requiring explicit min/max seems redundant.

Comment (zeitlinger) [reply server/zally-ruleset-zally/src/test/kotlin/de/zalando/zally/ruleset/zally/StringPropertyLengthBoundsRuleTest.kt:288]: ok, that was a bit indirect - but now I get it.

**Comment by zeitlinger** [comment]
:+1:
