### PR TITLE
BUGFIX: Path with trailing slash respond 403

### LINKED ISSUE #770: BUG: Requests with trailing slashes respond 403
How to reproduce:

```
curl -XPOST -v -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" --data "@test.yaml" "$ZALLY_SERVER/api-violations" | jq
```
yields
```json
{
  "title": "Forbidden",
  "status": 403,
  "detail": "Access is denied"
}
```

While without a trailing slash
```
curl -XPOST -v -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" --data "@test.yaml" "$ZALLY_SERVER/api-violations" | jq
```
authentifies correctly.

### PR DESCRIPTION
**Pull request by ddufourboivin-zalando**
closes #770 

Consider that there is no test on the OAUTH configuration at all. Please review carefully, since I am no Spring Security expert.

### CODE REVIEW

File: server/src/main/java/de/zalando/zally/configuration/OAuthConfiguration.java [hunk 1]
```diff
@@ -45,11 +45,13 @@ public void configure(final HttpSecurity http) throws Exception {
             .and()
             .authorizeRequests()
             .antMatchers(HttpMethod.OPTIONS, "/**").permitAll()
```
Comment (maxim-tschumak) [inline server/src/main/java/de/zalando/zally/configuration/OAuthConfiguration.java]: let's migrate this one also to `regexMatcher`

File: server/src/test/java/de/zalando/zally/configuration/PathMatchersTest.kt [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+import org.springframework.security.web.util.matcher.RegexRequestMatcher
+import javax.servlet.http.HttpServletRequest
+
+/**
+ * This serves as a reminder/documentation of how the matchers do work.
+ */
+class PathMatchersTest {
+
+    @Test
+    fun `antMatcher without trailing slash matches just requests without trailing slash`() {
```
Comment (maxim-tschumak) [inline server/src/test/java/de/zalando/zally/configuration/PathMatchersTest.kt]: Why do we need to test the `antMatcher`? (since we migrated all the filters to `regexMatcher`)

Comment (tkrop) [reply server/src/test/java/de/zalando/zally/configuration/PathMatchersTest.kt]: We should test the effectiveness of the configuration, not the working of configuration patterns :(.

Comment (maxim-tschumak) [reply server/src/test/java/de/zalando/zally/configuration/PathMatchersTest.kt]: In general, I agree with @tkrop. But I'm also OK with testing the effectiveness of the configuration since we had a problem with this critical part of the application and want to become more confident about the configuration.

Comment (ddufourboivin-zalando) [reply server/src/test/java/de/zalando/zally/configuration/PathMatchersTest.kt]: This "test" is there to show / explain / remind ourselves on what does what in terms of matchers and to make sure our assumptions are proven true.

As for testing the configuration, I welcome any idea or experience you might have in testing such a thing. In the current state of the application, I do not know how it is possible.

File: server/src/main/java/de/zalando/zally/configuration/OAuthConfiguration.java (hunk 1 above)
Comment (ddufourboivin-zalando) [reply server/src/main/java/de/zalando/zally/configuration/OAuthConfiguration.java]: I expect `regexMatchers` to be more runtime-costy than `antMatchers`. Since this one did not need a `regex` logic to work property, I voluntarily left it as is.

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍
